#include <stdint.h>
#include "tms320f2802xx.h"
#include "pie.h"

#ifdef FLASH
extern uint16_t RamfuncsLoadStart;
extern uint16_t RamfuncsLoadSize;
extern uint16_t RamfuncsRunStart;
extern uint16_t InitOnlyLoadStart;
extern uint16_t InitOnlyLoadSize;
extern uint16_t InitOnlyRunStart;

//#pragma CODE_SECTION(test,"ramfuncs")
#pragma CODE_SECTION(flash_config,"ramfuncs")
#endif
static void flash_config( void )
{
	// this has to be executed out of RAM.
	uint16_t delay = 3;
	FBANKWAIT = FBANKWAIT_PAGEWAIT(2)|FBANKWAIT_RANDWAIT(2);
	FOPT = FOPT_ENPIPE_ENABLE;
	while( delay-- );
}

int main(void)
{
	EALLOW();
	DINT();
	IER = 0;
	IFR = 0;

	Device_cal();

	CLKCTL =	CLKCTL_NMIRESETSEL_MCLKHS |
				CLKCTL_XTALOSCOFF_OFF |
				CLKCTL_XCLKINOFF_OFF |
				CLKCTL_WDHALTI_ON |
				CLKCTL_INTOSC2HALTI_ON |
				CLKCTL_INTOSC2OFF_OFF |
				CLKCTL_INTOSC1HALTI_ON |
				CLKCTL_INTOSC1OFF_ON |
				CLKCTL_TMR2CLKPRESCALE_DIV1 |			// CPU Timer 2 souce clock =
				CLKCTL_TMR2CLKSRCSEL_SYSCLKOUT |		// 60MHz
				CLKCTL_WDCLKSRCSEL_INTOSC1 |
				CLKCTL_OSCCLKSRC2SEL_INTOSC2 |
				CLKCTL_OSCCLKSRCSEL_INTOSC1;

	LOSPCP = 	LOSPCP_LSPCLK_DIV1;
	if( (PLLSTS & PLLSTS_MCLKSTS_MASK) == PLLSTS_MCLKSTS_MISSING )
	{
		PLLSTS |= PLLSTS_MCLKCLR_RESET;
		ESTOP0();
	}
	if( (PLLSTS & PLLSTS_DIVSEL_MASK) )
	{
		PLLSTS &= ~PLLSTS_DIVSEL_MASK;
	}
	PLLSTS = (PLLSTS & PLLSTS_MCLKOFF_MASK) | PLLSTS_MCLKOFF_DISABLE;
	PLLCR = PLLCR_DIV_12;
	while( PLLSTS & PLLSTS_PLLLOCKS_LOCKING );
	PLLSTS = (PLLSTS & (PLLSTS_MCLKOFF_MASK|PLLSTS_DIVSEL_MASK)) | PLLSTS_MCLKOFF_ENABLE|PLLSTS_DIVSEL_DIV2;
	XCLK = XCLK_XCLKINSEL_GPIO38 | XCLK_XCLKOUTDIV_DIV1;
	GPAMUX2 = 	GPAMUX2_GPIO29_GPIO |
				GPAMUX2_GPIO28_GPIO |
				GPAMUX2_GPIO19_GPIO |
				GPAMUX2_GPIO18_XCLKOUT;
	GPAMUX1 = 	GPAMUX1_GPIO12_GPIO |
				GPAMUX1_GPIO7_GPIO |
				GPAMUX1_GPIO6_GPIO |
				GPAMUX1_GPIO5_GPIO |
				GPAMUX1_GPIO4_GPIO |
				GPAMUX1_GPIO3_GPIO |
				GPAMUX1_GPIO2_GPIO |
				GPAMUX1_GPIO1_GPIO |
				GPAMUX1_GPIO0_EPWM1A;
	GPAPUD = 	GPAPUD_DISABLE(0)|GPAPUD_DISABLE(1)|GPAPUD_DISABLE(2)|GPAPUD_DISABLE(3);
	GPADIR = GPADIR_OUTPUT(0)|GPADIR_OUTPUT(1)|GPADIR_OUTPUT(2)|GPADIR_OUTPUT(3);
	GPASET = GPA_MASK(0)|GPA_MASK(1)|GPA_MASK(2)|GPA_MASK(3);



#ifdef FLASH
	memcpy(&RamfuncsRunStart, &RamfuncsLoadStart, (int16_t)&RamfuncsLoadSize);
//	memcpy(&InitOnlyRunStart, &InitOnlyLoadStart, (int16_t)&InitOnlyLoadSize);
#endif

	flash_config();
	pie_init();

	SET_TIMER_PRESCALE(2,60000);	// timer2 = 1ms tick rate
	SET_TIMER_PERIOD(2,100);	// 10Hz
	TIMERTCR(2) = TIMERTCR_TIE_ENABLE | TIMERTCR_FREE_SOFT_HARDSTOP | TIMERTCR_TRB_RELOAD | TIMERTCR_TSS_RUNNING;

	pie_init();
	IER = CPU_INT14;
	IFR = 0;

		// Enable PWM clock
	PCLKCR1 = 	PCLKCR1_ECAP1ENCLK_DISABLE |
				PCLKCR1_EPWM4ENCLK_DISABLE |
				PCLKCR1_EPWM3ENCLK_DISABLE |
				PCLKCR1_EPWM2ENCLK_DISABLE |
				PCLKCR1_EPWM1ENCLK_ENABLE;

	TBCTL(1) =	TBCTL_FREE_SOFT_FREE_RUN |
				TBCTL_PHSDIR_COUNT_DOWN |
				TBCTL_CLKDIV_1 |
				TBCTL_HSPCLKDIV_2 |
				TBCTL_SYNCOSEL_CTR_ZERO |
				TBCTL_PRDLD_IMMEDIATE |
				TBCTL_PHSEN_NOLOAD |
				TBCTL_CTRMODE_UP_COUNT;

	AQCTLA(1) = AQCTL_CBD_DISABLE |
				AQCTL_CBU_DISABLE |
				AQCTL_CAD_DISABLE |
				AQCTL_CAU_SET |
				AQCTL_PRD_TOGGLE |
				AQCTL_ZRO_DISABLE;

	TBPRD(1) = 6000;
	CMPA(1) = 0;
	TBCTR(1) = 0;

	PCLKCR0 = 	PCLKCR0_SCIAENCLK_DISABLE |
				PCLKCR0_SPIAENCLK_DISABLE |
				PCLKCR0_I2CAENCLK_DISABLE |
				PCLKCR0_ADCENCLK_DISABLE |
				PCLKCR0_TBCLKSYNC_ENABLE |
				PCLKCR0_HRPWMENCLK_DISABLE;
	EINT();
	ERTM();
	EDIS();

	while( 1 )
	{
	}
}


